const beforeGuideModels=renderModels;
renderModels=function(){
  beforeGuideModels();
  $('.workspace-heading').insertAdjacentHTML('beforeend','<button class="outline-button models-guide-button" id="model-guide-open">'+icon('help')+'Как подключить модель</button>');
  $('#model-guide-open').onclick=openModelGuide;
  if($('#model-form')){
    $('#model-form').insertAdjacentHTML('afterbegin','<div class="model-guide-callout"><span>Подключаете модель впервые?</span><button type="button" id="form-model-guide">Пошаговая инструкция '+icon('forward')+'</button></div>');
    $('#form-model-guide').onclick=openModelGuide;
  }
  drawIcons($('#workspace-panel'));
};
function openModelGuide(){
  simpleDialog('Как подключить свою модель',`<div class="model-guide"><p class="guide-intro">Понадобятся API-ключ, адрес API и идентификатор модели выбранного сервиса.</p><ol class="connection-guide-steps"><li><h3>Получите доступ к API провайдера</h3><p>В кабинете сервиса создайте API-ключ и проверьте, что выбранная модель доступна вашему аккаунту. Адрес API и точное имя модели возьмите из документации провайдера.</p><div class="guide-provider-links"><a href="https://developers.openai.com/api/reference/overview#authentication" target="_blank" rel="noopener noreferrer">OpenAI ↗</a><a href="https://api-docs.deepseek.com/" target="_blank" rel="noopener noreferrer">DeepSeek ↗</a><a href="https://platform.claude.com/docs/en/api/overview" target="_blank" rel="noopener noreferrer">Claude ↗</a></div></li><li><h3>Добавьте подключение в Ведараме</h3><p>Откройте «Мои модели → Добавить подключение». Выберите провайдера. Для другого сервиса используйте «Свой API URL».</p></li><li><h3>Заполните данные</h3><dl><dt>Название подключения</dt><dd>Любое удобное имя, например «Для изучения шастр».</dd><dt>Идентификатор модели</dt><dd>Точное имя из каталога провайдера, а не название приложения или чата. Предзаполненное значение можно заменить.</dd><dt>API URL</dt><dd>Базовый адрес API. Для готового провайдера он подставляется автоматически; для своего сервиса скопируйте его из документации.</dd><dt>API-ключ</dt><dd>Ключ из кабинета того же сервиса. Не публикуйте его в сообщениях или снимках экрана.</dd></dl></li><li><h3>Проверьте и сохраните</h3><p>Нажмите «Проверить подключение», затем «Сохранить подключение». В дополнительных параметрах оставьте протокол «Автоматически», если провайдер не требует другой настройки.</p></li><li><h3>Выберите модель для задачи</h3><p>В чате откройте список над диалогом. Для AI-поиска выберите модель в разделе «Поиск». У чата и поиска могут быть разные модели.</p></li></ol><div class="guide-demo-note"><strong>Как попробовать в этом макете</strong><p>Введите <code>demo-key</code> вместо настоящего ключа. Проверка здесь проверяет форму, без обращения к API. Сохраняются настройки, но не ключ. Реальное подключение выполняется в рабочем приложении.</p></div><h3>Если подключение не работает</h3><div class="guide-troubleshooting"><details><summary>Нет доступа к сервису</summary><p>Проверьте API-ключ, права доступа к модели и состояние аккаунта провайдера.</p></details><details><summary>Модель не найдена</summary><p>Сверьте идентификатор с каталогом провайдера. Убедитесь, что модель доступна по указанному API URL.</p></details><details><summary>Сервис не отвечает или формат не подходит</summary><p>Проверьте адрес API и сеть. Для собственного сервиса сверьте выбранный протокол с его документацией.</p></details></div><button class="gold-button" id="guide-done">Вернуться к настройке</button></div>`);
  $('#dialog').classList.add('model-guide-dialog');
  $('#guide-done').onclick=()=>$('#dialog').close();
  $('#dialog').addEventListener('close',()=>$('#dialog').classList.remove('model-guide-dialog'),{once:true});
}
if(section==='models')renderModels();
