// Local prototype flows. No backend requests or external messages.
const escapeText=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const newId=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
if(!Array.isArray(saved.notes))saved.notes=[{id:'initial',text:typeof saved.note==='string'?saved.note:'Сравнить с БГ 2.48. Как связаны непривязанность и равновесие?',quote:'Отказ от привязанности к плодам не означает отказа от самого действия.'}];
if(!Array.isArray(saved.shelves))saved.shelves=[{id:'daily',name:'Для ежедневного чтения',books:['Бхагавад-гита']},{id:'sanskrit',name:'Изучение санскрита',books:[]}];
let editId=null,selectedQuote='',selectionRange=null;
function renderNotes(){const list=$('#notes-list');list.innerHTML=saved.notes.length?saved.notes.map(n=>`<article class="note-card" data-note-id="${escapeText(n.id)}"><div class="note-caption">ЗАМЕТКА<div><button data-edit="${escapeText(n.id)}" aria-label="Редактировать заметку" title="Редактировать"><i data-icon="note"></i></button><button data-delete="${escapeText(n.id)}" aria-label="Удалить заметку" title="Удалить"><i data-icon="close"></i></button></div></div>${n.quote?`<blockquote>${escapeText(n.quote)}</blockquote>`:''}<p class="note-content">${escapeText(n.text)}</p></article>`).join(''):'<div class="empty-state"><i data-icon="note"></i><h3>Здесь будут ваши заметки</h3><p>Добавьте мысль ко всему стиху или сначала выделите фрагмент книги.</p></div>';
const linked=saved.notes.filter(n=>n.quote===document.querySelector('#annotation').textContent);document.querySelector('.inline-note').hidden=!linked.length;document.querySelector('.inline-note').textContent=linked.length;document.querySelector('#annotation').classList.toggle('unannotated',!linked.length);document.querySelectorAll('[data-note-count]').forEach(el=>el.textContent=saved.notes.length);$('#notes-summary').textContent=saved.notes.length?'К этому стиху · '+saved.notes.length:'Пока нет заметок';
list.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>startNote(saved.notes.find(n=>n.id===b.dataset.edit)));
list.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const index=saved.notes.findIndex(n=>n.id===b.dataset.delete),removed=saved.notes[index];saved.notes.splice(index,1);if(editId===removed.id)cancelNote();persist();renderNotes();toast('Заметка удалена.');const undo=document.createElement('button');undo.textContent='Отменить';undo.onclick=()=>{if(!saved.notes.some(n=>n.id===removed.id))saved.notes.splice(Math.min(index,saved.notes.length),0,removed);persist();renderNotes();$('.toast').hidden=true;};$('.toast').append(undo);clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('.toast').hidden=true,9000);});drawIcons(list);}
function startNote(note=null){setView('notes');if(!$('#note-editor').hidden&&$('#note-text').value.trim()&&editId!==note?.id){toast('Сначала сохраните или отмените открытую заметку.');$('#note-text').focus();return;}editId=note?.id||null;$('#note-text').value=note?.text||'';$('#note-quote').textContent=note?.quote||selectedQuote;$('#note-quote').hidden=!$('#note-quote').textContent;$('#note-editor').hidden=false;$('#selection-actions').hidden=true;$('#note-text').focus();$('#note-editor').scrollIntoView({block:'nearest'});}
function cancelNote(){$('#note-editor').hidden=true;$('#note-text').value='';editId=null;selectedQuote='';}
$('#add-note').onclick=()=>startNote();$('#cancel-note').onclick=cancelNote;
$('#note-editor').onsubmit=e=>{e.preventDefault();const text=$('#note-text').value.trim();if(!text){$('#note-text').setCustomValidity('Введите текст заметки');$('#note-text').reportValidity();return;}const note={id:editId||newId(),text,quote:$('#note-quote').textContent};const old=saved.notes.findIndex(n=>n.id===note.id);if(old<0)saved.notes.push(note);else saved.notes[old]=note;const stored=persist();cancelNote();renderNotes();toast(stored?'Заметка сохранена на этом устройстве':'Заметка доступна в этой вкладке. Локальное сохранение недоступно.');};
$('#note-text').oninput=()=>$('#note-text').setCustomValidity('');
document.addEventListener('selectionchange',()=>{const s=getSelection();if(!s?.rangeCount||s.isCollapsed){$('#selection-actions').hidden=true;return;}const range=s.getRangeAt(0);const node=range.commonAncestorContainer;if(!$('.book-page').contains(node)||!s.toString().trim())return;selectedQuote=s.toString().trim().slice(0,1800);selectionRange=range.cloneRange();const r=range.getBoundingClientRect(),bar=$('#selection-actions');bar.hidden=false;bar.style.top=Math.max(80,Math.min(innerHeight-80,r.bottom+8))+'px';bar.style.left=Math.max(12,Math.min(innerWidth-245,r.left))+'px';});
$('#annotate-selection').onpointerdown=e=>e.preventDefault();$('#annotate-selection').onclick=()=>startNote();
renderNotes();

function renderShelvesNav(){const el=$('#personal-shelves');el.innerHTML='<div class="section-label">МОИ ПОЛКИ<button class="icon-button" aria-label="Создать полку" title="Создать полку"><i data-icon="plus"></i></button></div>'+saved.shelves.map(s=>`<button data-shelf="${escapeText(s.id)}"><i data-icon="shelf"></i><span class="shelf-name">${escapeText(s.name)}</span><span>${s.books.length}</span></button>`).join('');el.querySelectorAll('button').forEach(b=>b.onclick=()=>openDialog('shelves'));drawIcons(el);}
function shelvesDialog(){const body=$('#dialog-body');body.innerHTML=`<p>Подборки книг и томов. Изменение полки не меняет каталог.</p><div class="shelf-list">${saved.shelves.map(s=>`<article class="shelf-card"><div class="shelf-heading"><strong>${escapeText(s.name)}</strong><button data-rename="${s.id}" title="Переименовать полку" aria-label="Переименовать полку"><i data-icon="note"></i></button></div><p>${s.books.length?escapeText(s.books.join(', ')):'Пока нет книг'}</p><button class="outline-button" data-add-book="${s.id}" ${s.books.includes('Бхагавад-гита')?'disabled':''}>${s.books.includes('Бхагавад-гита')?'✓ Бхагавад-гита на полке':'+ Добавить текущую книгу'}</button></article>`).join('')}</div><form id="shelf-form"><h3 id="shelf-form-title">Новая полка</h3><label for="shelf-name">Название</label><input class="wide" id="shelf-name" maxlength="60" required placeholder="Например, Изучение Гиты"><p id="shelf-error" role="alert"></p><div class="editor-actions"><button type="button" id="cancel-shelf" hidden>Отмена</button><button class="gold-button" id="create-shelf" type="submit">Создать полку</button></div></form><p class="panel-hint">Сохраняется на этом устройстве.</p>`;
let renameId=null;body.querySelectorAll('[data-add-book]').forEach(b=>b.onclick=()=>{saved.shelves.find(s=>s.id===b.dataset.addBook).books.push('Бхагавад-гита');persist();renderShelvesNav();shelvesDialog();});body.querySelectorAll('[data-rename]').forEach(b=>b.onclick=()=>{renameId=b.dataset.rename;$('#shelf-form-title').textContent='Переименовать полку';$('#create-shelf').textContent='Сохранить';$('#cancel-shelf').hidden=false;$('#shelf-name').value=saved.shelves.find(s=>s.id===renameId).name;$('#shelf-name').focus();});$('#cancel-shelf').onclick=shelvesDialog;
$('#shelf-form').onsubmit=e=>{e.preventDefault();const name=$('#shelf-name').value.trim().replace(/\s+/g,' ');if(!name){$('#shelf-error').textContent='Введите название полки.';return;}if(saved.shelves.some(s=>s.id!==renameId&&s.name.toLocaleLowerCase()===name.toLocaleLowerCase())){$('#shelf-error').textContent='Полка с таким названием уже есть.';return;}if(renameId)saved.shelves.find(s=>s.id===renameId).name=name;else saved.shelves.push({id:newId(),name,books:[]});persist();renderShelvesNav();shelvesDialog();};drawIcons(body);}
renderShelvesNav();

const originalOpenDialog=openDialog;
openDialog=function(key){originalOpenDialog(key);if(key==='shelves')shelvesDialog();if(key==='settings'){const preview=document.createElement('div');preview.className='settings-preview';preview.innerHTML='<span>ПРЕДПРОСМОТР</span><p>karmaṇy evādhikāras te</p><p>Текст книги остаётся читаемым.</p>';$('#dialog-body .setting-row').after(preview);const updatePreview=()=>preview.style.fontSize=(saved.size||19)+'px';$('#font-size').addEventListener('input',updatePreview);updatePreview();}if(key==='support'){const p=document.createElement('p');p.className='panel-hint';p.textContent='Сообщение можно сохранить черновиком и продолжить позже.';const button=document.createElement('button');button.className='gold-button';button.textContent='Сохранить черновик';const text=$('#dialog-body textarea');text.value=saved.supportDraft||'';button.onclick=()=>{saved.supportDraft=text.value;const ok=persist();if(ok)toast('Черновик сохранён. Сообщение не отправлялось.');};$('#dialog-body').append(p,button);}};

const question=$('#ai-question');question.value=saved.aiDraft||'';
function updateQuestion(){$('#ask-ai').disabled=!question.value.trim();saved.aiDraft=question.value;persist();}
question.addEventListener('input',updateQuestion);$('#ask-ai').disabled=!question.value.trim();
document.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>{question.value=b.dataset.question;updateQuestion();question.focus();});
$('#context-pin').onclick=()=>{const active=$('#context-pin').getAttribute('aria-pressed')!=='true';$('#context-pin').setAttribute('aria-pressed',String(active));$('#context-pin').textContent=active?'Закреплён':'За чтением';$('#context-pin').title=active?'Контекст не изменится при переходе к другому стиху':'Контекст следует за текущим стихом';};
$('#ai-form').onsubmit=e=>{e.preventDefault();const value=question.value.trim();if(!value)return;const messages=$('#ai-messages');const turn=document.createElement('article');turn.className='ai-turn';turn.innerHTML=`<div class="question-bubble">${escapeText(value)}</div><span class="demo-answer-label">Пример ответа · демонстрация</span><p>Здесь появится ответ по выбранному контексту. Ссылки на использованные фрагменты будут открываться в книге рядом с диалогом.</p><button class="source-link">Бхагавад-гита · 2.47 ↗</button>`;turn.querySelector('button').onclick=()=>{$('.book-heading').scrollIntoView({block:'start'});$('.book-heading').classList.add('source-highlight');setTimeout(()=>$('.book-heading').classList.remove('source-highlight'),1800);};messages.append(turn);$('.ai-intro').hidden=true;$('.suggestions').hidden=true;question.value='';updateQuestion();$('#ai-scroll').scrollTop=$('#ai-scroll').scrollHeight;};
const previousFocus=$('#focus').onclick;let beforeFocus='read';$('#focus').onclick=()=>{const entering=!document.body.classList.contains('focus-mode');if(entering)beforeFocus=view;previousFocus();if(!entering)setView(beforeFocus);$('#focus span').textContent=entering?'Выйти из чтения':'Режим чтения';};
$('#toggle-tree').onclick=()=>{if(innerWidth<=700){const show=!document.body.classList.contains('mobile-tree');setView('read');document.body.classList.toggle('mobile-tree',show);$('#toggle-tree').setAttribute('aria-expanded',String(show));return;}const hidden=getComputedStyle($('.catalog')).display==='none';if(hidden){document.body.classList.remove('tree-hidden','focus-mode');if(innerWidth<=1150)setView('read');}else document.body.classList.add('tree-hidden');$('#toggle-tree').setAttribute('aria-label',hidden?'Скрыть дерево книг':'Показать дерево книг');$('#toggle-tree').setAttribute('aria-expanded',String(hidden));};
// Icon characters without a close action misrepresented working tab controls.
document.querySelectorAll('.book-tab>span').forEach(s=>s.remove());
const shortcut=navigator.platform.toLowerCase().includes('mac')?'⌘':'Ctrl';$('.global-search kbd').textContent=shortcut+' K';$('#new-tab').title='Открыть книгу';$('#back').title='Назад';$('#forward').title='Вперёд';
document.querySelectorAll('.rail-item[data-view],.rail-item[data-dialog]').forEach(b=>b.setAttribute('data-tip',b.title));
drawIcons();
