const $ = s => document.querySelector(s);
const icons = {
 panel:'M3 4h18v16H3z M8 4v16',back:'M19 12H5 M11 6l-6 6 6 6',forward:'M5 12h14 M13 6l6 6-6 6',search:'M10.5 18a7.5 7.5 0 1 0 0-15 7.5 7.5 0 0 0 0 15 M16 16l5 5',book:'M12 5C8 2 4 3 2 4v16c4-2 7-1 10 1 3-2 6-3 10-1V4c-3-1-6-2-10 1z M12 5v16',settings:'M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1z M16 12a4 4 0 1 0-8 0 4 4 0 0 0 8 0',folder:'M3 5h7l2 3h9v13H3z',shelf:'M3 4v16h18V4 M4 15h16 M7 6v9 M11 5v10 M15 7l3 8',bookmark:'M6 3h12v18l-6-4-6 4z',note:'M5 3h14v18H5z M8 8h8 M8 12h8 M8 16h4',help:'M21 12a9 9 0 1 0-18 0 9 9 0 0 0 18 0 M9 9a3 3 0 1 1 4 3l-1 1v1 M12 17h.01',down:'M6 9l6 6 6-6',right:'M9 6l6 6-6 6',plus:'M12 5v14 M5 12h14',download:'M12 3v12 M7 10l5 5 5-5 M4 16v5h16v-5',spark:'M12 3l2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5z M20 2v4 M18 4h4',close:'M6 6l12 12 M18 6 6 18',pin:'M9 3h6v5l3 4v2H6v-2l3-4z M12 14v7',check:'M4 12l5 5L20 6',globe:'M21 12a9 9 0 1 0-18 0 9 9 0 0 0 18 0 M3 12h18 M12 3c5 5 5 13 0 18-5-5-5-13 0-18'
};
function drawIcons(root=document){root.querySelectorAll('i[data-icon]').forEach(i=>{i.innerHTML=`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[i.dataset.icon]||icons.book}"/></svg>`;});}
drawIcons();
let view='read',toastTimer;
let saved={};try{saved=JSON.parse(localStorage.getItem('vedarama-light-mockup-v1')||'{}');}catch{}
function persist(){try{localStorage.setItem('vedarama-light-mockup-v1',JSON.stringify(saved));return true;}catch{toast('Не удалось сохранить на устройстве. Не закрывайте страницу до копирования заметки.');return false;}}
function toast(message){const t=$('.toast');t.textContent=message;t.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.hidden=true,4300);}
function setView(next){view=next;$('#inspector').hidden=next==='read';$('#notes-panel').hidden=next!=='notes';$('#ai-panel').hidden=next!=='ai';document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===next);b.setAttribute('aria-pressed',String(b.dataset.view===next));});}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
setView(['read','notes','ai'].includes(new URLSearchParams(location.search).get('view'))?new URLSearchParams(location.search).get('view'):'read');
$('#toggle-tree').onclick=()=>{if(innerWidth<=700){document.body.classList.toggle('mobile-tree');return;}document.body.classList.toggle('tree-hidden');const hidden=document.body.classList.contains('tree-hidden');$('#toggle-tree').setAttribute('aria-label',hidden?'Показать дерево книг':'Скрыть дерево книг');$('#toggle-tree').setAttribute('aria-expanded',String(!hidden));};
$('#focus').onclick=()=>{document.body.classList.toggle('focus-mode');$('#focus').setAttribute('aria-pressed',String(document.body.classList.contains('focus-mode')));if(document.body.classList.contains('focus-mode'))setView('read');};
function updateBookmark(){const active=!!saved.bookmark;$('#bookmark').setAttribute('aria-pressed',String(active));$('#bookmark').setAttribute('aria-label',active?'Удалить закладку':'Добавить закладку');$('#bookmark').title=active?'Удалить закладку':'Добавить закладку';}
$('#bookmark').onclick=()=>{saved.bookmark=!saved.bookmark;persist();updateBookmark();toast(saved.bookmark?'БГ 2.47 добавлен в закладки':'Закладка удалена');};updateBookmark();



document.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>{$('#ai-question').value=b.dataset.question;$('#ai-question').focus();});

const pageMessages=()=>toast('В макете показан БГ 2.47. Переходы к другим стихам будут доступны в приложении.');
['back','forward','previous-verse','next-verse','bottom-prev','bottom-next'].forEach(id=>$('#'+id).onclick=pageMessages);
document.querySelectorAll('[data-verse]').forEach(b=>b.onclick=()=>{if(b.dataset.verse!=='47')pageMessages();});
$('#catalog-search').oninput=e=>{const q=e.target.value.trim().toLowerCase();document.querySelectorAll('.tree button').forEach(b=>b.hidden=!!q&&!b.textContent.toLowerCase().includes(q));};
document.querySelectorAll('[data-catalog]').forEach(b=>b.onclick=()=>toast(`Раздел «${b.dataset.catalog}» сохраняется в приложении. Макет показывает дерево категорий.`));
$('#search-form').onsubmit=e=>{e.preventDefault();openDialog('search');};
$('#new-tab').onclick=()=>openDialog('catalog');
function applySettings(){document.documentElement.style.setProperty('--reader-size',(saved.size||19)+'px');document.documentElement.style.setProperty('--ui-size',(saved.uiSize||14)+'px');document.documentElement.style.setProperty('--ui-scale',(saved.uiSize||14)/14);document.documentElement.style.removeProperty('--gold');if('gold' in saved){delete saved.gold;persist();}document.querySelectorAll('[data-block]').forEach(b=>b.hidden=saved.blocks?.[b.dataset.block]===false);}
applySettings();
const descriptions={
 brief:['Светлая тема. Знакомая Ведарама',`<p>Один основной экран чтения и два состояния правой панели. Во всех состояниях светлые дерево, навигация, вкладки, диалоги и текст.</p><h3>Сохраняем дизайн-систему</h3><p>Реальный значок приложения, PT Sans и Gaura PT Serif. Цвета взяты из исходников: золотое выделение #EFC869, акценты #B78A54 и #C99C66, светлые поверхности #FEFEFE и #EDEDEE.</p><h3>Обновляем небольшие детали</h3><ul><li>Ровные отступы, тонкие разделители, скругления 2–4 px.</li><li>Скрытие дерева одной кнопкой, короткая панель действий над текстом.</li><li>Заметки и AI рядом с чтением; контекст AI закреплён за стихом.</li><li>Мои полки, закладки, поддержка, статус онлайн-чтения при загрузке.</li></ul><p>В этой демонстрации можно переключать панели, скрывать дерево, менять размер текста, создавать и редактировать заметки, собирать полки и сохранять закладки локально. Поиск, AI, загрузки и отправка в поддержку показаны как будущие функции.</p><div class="chips"><a href="screens/light-read.png" target="_blank" rel="noopener">PNG: чтение</a><a href="screens/light-notes.png" target="_blank" rel="noopener">PNG: заметки</a><a href="screens/light-ai.png" target="_blank" rel="noopener">PNG: AI</a></div><a class="brief-link" href="implementation-brief.md">Полный список требований и этапы внедрения ↗</a>`],
 settings:['Вид текста и интерфейса',`<div class="theme-selected"><span>☀ Светлая тема · весь интерфейс</span><span>✓</span></div><p class="panel-hint">Тёмную и мягкую темы проработаем следующим этапом.</p><div class="setting-row"><label>Размер текста книги <input id="font-size" type="range" min="16" max="26" value="${saved.size||19}"><output id="font-value">${saved.size||19} px</output></label><label>Размер интерфейса <input id="ui-size" type="range" min="14" max="18" value="${saved.uiSize||14}"><output id="ui-value">${saved.uiSize||14} px</output></label><p class="panel-hint">PT Sans — интерфейс. Gaura PT Serif — книга.</p></div><h3>Показывать в книге</h3>${[['original','Оригинал и транслитерация'],['gloss','Пословный перевод'],['translation','Перевод'],['comment','Комментарий']].map(([id,title])=>`<label>${title}<input type="checkbox" data-block-setting="${id}" ${saved.blocks?.[id]===false?'':'checked'}></label>`).join('')}<p class="panel-hint">Изменения сохраняются локально в этом браузере. Базовый макет использует исходную палитру приложения.</p><button class="outline-button" id="reset-settings">Вернуть исходные настройки</button>`],
 shelves:['Мои полки',`<p>Книги и отдельные тома можно собирать в свои подборки, сохраняя исходное дерево библиотеки.</p><div class="chips"><span>Для ежедневного чтения · 4</span><span>Изучение санскрита · 7</span></div><h3>Новая полка</h3><label>Название<input id="shelf-name" placeholder="Например, Изучение Гиты"></label><button class="gold-button" id="create-shelf">Создать полку</button><div id="shelf-result"></div><p class="panel-hint">Локальная демонстрация. Полка не изменяет каталог и не копирует книги.</p>`],
 bookmarks:['Закладки',`<p>${saved.bookmark?'Бхагавад-гита · Глава 2 · Текст 47':'Пока нет закладок. Нажмите значок закладки над текстом.'}</p><p class="panel-hint">Закладки и последняя позиция чтения — разные сохранённые данные.</p>`],
 converter:['Транслитерация',`<p>Привычный конвертор сохраняется в левой панели.</p><label>Из<select><option>IAST</option><option>Деванагари</option><option>Кириллица</option></select></label><label>В<select><option>Кириллица</option><option>IAST</option><option>Деванагари</option></select></label><textarea aria-label="Исходный текст транслитерации" placeholder="Вставьте текст…"></textarea><p class="panel-hint">В этом макете преобразование не выполняется. Корректность диакритики и поддерживаемых схем — отдельная задача реализации.</p>`],
 support:['Написать в поддержку',`<label>Тема<select><option>Неполадка в приложении</option><option>Пожелание</option><option>Ошибка в тексте</option></select></label><textarea aria-label="Сообщение в поддержку" placeholder="Опишите, что произошло и что вы ожидали…"></textarea><label><span>Приложить диагностику после просмотра</span><input type="checkbox"></label><p class="panel-hint">В макете сообщения никуда не отправляются. В приложении перед отправкой можно будет проверить вложения.</p>`],
 catalog:['Новая вкладка',`<p>В новой вкладке можно открыть книгу или продолжить поиск по библиотеке.</p><label>Книга<input placeholder="Название или автор" aria-label="Название или автор"></label><p class="panel-hint">Демонстрация основного экрана ограничена БГ 2.47. Полный каталог и переключение языков подключаются при реализации.</p>`],
 search:['Поиск по библиотеке',`<label>Режим<select><option>Обычный поиск</option><option>Поиск с AI</option></select></label><label>Область<select><option>Вся библиотека</option><option>Текущая книга</option><option>Мои полки</option></select></label><p>Обычная выдача остаётся самостоятельной. AI сможет искать связанные места и приводить ссылки на источники.</p><p class="panel-hint">Поисковый сервис в этом макете не подключён.</p>`]
};
function openDialog(key){const entry=descriptions[key]||descriptions.brief;$('#dialog-title').textContent=entry[0];$('#dialog-body').innerHTML=entry[1];$('#dialog').showModal();
if(key==='settings'){
 const size=$('#font-size'),ui=$('#ui-size');size.value=saved.size||19;ui.value=saved.uiSize||14;$('#font-value').textContent=size.value+' px';$('#ui-value').textContent=ui.value+' px';document.querySelectorAll('[data-block-setting]').forEach(c=>{c.checked=saved.blocks?.[c.dataset.blockSetting]!==false;c.onchange=()=>{saved.blocks={...saved.blocks,[c.dataset.blockSetting]:c.checked};persist();applySettings();};});
 size.oninput=()=>{saved.size=Number(size.value);$('#font-value').textContent=size.value+' px';persist();applySettings();};ui.oninput=()=>{saved.uiSize=Number(ui.value);$('#ui-value').textContent=ui.value+' px';persist();applySettings();};$('#reset-settings').onclick=()=>{delete saved.size;delete saved.uiSize;delete saved.gold;delete saved.blocks;persist();applySettings();$('#dialog').close();openDialog('settings');};
}if(key==='bookmarks')$('#dialog-body').firstElementChild.textContent=saved.bookmark?'Бхагавад-гита · Глава 2 · Текст 47':'Пока нет закладок. Нажмите значок закладки над текстом.';
if(key==='shelves')$('#create-shelf').onclick=()=>{const name=$('#shelf-name').value.trim();if(!name)return;const p=document.createElement('p');p.textContent='Полка «'+name+'» создана в демонстрации.';$('#shelf-result').replaceChildren(p);};}
document.querySelectorAll('[data-dialog]').forEach(b=>b.onclick=()=>openDialog(b.dataset.dialog));
$('#close-dialog').onclick=()=>$('#dialog').close();
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('.global-search input').focus();}if((e.metaKey||e.ctrlKey)&&e.shiftKey&&e.key.toLowerCase()==='r'){e.preventDefault();$('#focus').click();}});
