'use strict';
(() => {
const variants=[{"file":"01-quiet-reading.png","name":"Тихая читальня","desc":"Мягкий фон, зелёный акцент и просторная область чтения.","number":1,"type":"","shape":"","palette":[],"layout":"Мягкий фон, зелёный акцент и просторная область чтения."},{"file":"02-research-desk.png","name":"Исследовательский стол","desc":"Работа с текстом, источниками и контекстным AI.","number":2,"type":"","shape":"","palette":[],"layout":"Работа с текстом, источниками и контекстным AI."},{"file":"03-personal-library.png","name":"Живая библиотека","desc":"Личные полки, подборки и продолжение чтения.","number":3,"type":"","shape":"","palette":[],"layout":"Личные полки, подборки и продолжение чтения."},{"file":"04-editorial-reader.png","name":"Редакционная читалка","desc":"Книжная типографика и заметки на полях.","number":4,"type":"","shape":"","palette":[],"layout":"Книжная типографика и заметки на полях."},{"file":"05-flexible-minimal.png","name":"Гибкий минимализм","desc":"Настройка цветов, размеров шрифтов и оформления под себя.","number":5,"type":"","shape":"","palette":[],"layout":"Настройка цветов, размеров шрифтов и оформления под себя."},{"file":"07-sand-reader.png","name":"Терракота · песочная палитра","desc":"Светлая бумага, сдержанные оливково-коричневые акценты и книжная антиква.","type":"Книжная антиква","shape":"0 px","layout":"Оглавление сверху · заметка на поле","palette":["#F5F1E7","#33372F","#6F7458"],"number":7},{"file":"08-sage-reader.png","name":"Шалфей","desc":"Зелёный фон, мягкая типографика, крупные радиусы и плавающие панели.","type":"Мягкий гуманистический шрифт","shape":"24–32 px","layout":"Плавающее оглавление · округлая страница","palette":["#DCE8D8","#FAFCF5","#244A3D"],"number":8},{"file":"09-charcoal-reader.png","name":"Полночь","desc":"Тёплый угольный фон, мягкое золото и контрастный светлый текст.","type":"Гротеск + моноширинные метаданные","shape":"2–4 px","layout":"Оглавление справа · заметки снизу","palette":["#1C1E1B","#E8E6DC","#C2AC77"],"number":9},{"file":"10-stone-reader.png","name":"Камень и бронза","desc":"Тёплые каменные оттенки, графит и приглушённая бронза. Компоновка и формы лилового концепта сохранены.","type":"Геометрический гротеск","shape":"16 px и кнопки-капсулы","layout":"Заметки слева · оглавление снизу · инструменты справа","palette":["#E7E3DA","#393A35","#B49A62"],"number":10}];
for (const slot of ['A','B']) {
 const select=document.getElementById('select-'+slot);
 select.addEventListener('change',()=>{
  const variant=variants[Number(select.value)]; if(!variant)return;
  const img=document.getElementById('image-'+slot);img.src=variant.file;img.alt=variant.name+': '+variant.desc;
  document.getElementById('link-'+slot).href=variant.file;document.getElementById('full-'+slot).href=variant.file;
  document.getElementById('meta-'+slot).textContent=[variant.type,variant.shape].filter(Boolean).join(' · ');
  document.getElementById('layout-'+slot).textContent=variant.layout;
  const swatches=document.getElementById('swatches-'+slot);swatches.replaceChildren(...variant.palette.map(color=>{const item=document.createElement('i');item.style.background=color;item.title=color;return item;}));
 });
}

})();
