'use strict';
(() => {
const variants=[{"file":"01-quiet-main.png","name":"Тихая читальня","desc":"Основной экран чтения: тёплый кремовый фон, зелёные акценты, оглавление и заметки.","number":1,"type":"","shape":"","palette":[],"layout":"Основной экран чтения: тёплый кремовый фон, зелёные акценты, оглавление и заметки."},{"file":"02-research-main.png","name":"Исследовательский стол","desc":"Основной экран чтения в тёмном исследовательском стиле: компактная навигация, текст и заметки.","number":2,"type":"","shape":"","palette":[],"layout":"Основной экран чтения в тёмном исследовательском стиле: компактная навигация, текст и заметки."},{"file":"03-library-main.png","name":"Живая библиотека","desc":"Открытая книга в мягкой минеральной палитре с оглавлением и заметкой.","number":3,"type":"","shape":"","palette":[],"layout":"Открытая книга в мягкой минеральной палитре с оглавлением и заметкой."},{"file":"04-editorial-main.png","name":"Редакционная читалка","desc":"Основной экран чтения с книжной типографикой, бордовыми акцентами и заметкой на полях.","number":4,"type":"","shape":"","palette":[],"layout":"Основной экран чтения с книжной типографикой, бордовыми акцентами и заметкой на полях."},{"file":"05-minimal-main.png","name":"Гибкий минимализм","desc":"Минималистичная читалка с компактной навигацией, четырьмя блоками текста и заметкой.","number":5,"type":"","shape":"","palette":[],"layout":"Минималистичная читалка с компактной навигацией, четырьмя блоками текста и заметкой."},{"file":"07-sand-reader.png","name":"Терракота · песочная палитра","desc":"Светлая бумага, сдержанные оливково-коричневые акценты и книжная антиква.","type":"Книжная антиква","shape":"0 px","layout":"Оглавление сверху · заметка на поле","palette":["#F5F1E7","#33372F","#6F7458"],"number":7},{"file":"08-sage-reader.png","name":"Шалфей","desc":"Зелёный фон, мягкая типографика, крупные радиусы и плавающие панели.","type":"Мягкий гуманистический шрифт","shape":"24–32 px","layout":"Плавающее оглавление · округлая страница","palette":["#DCE8D8","#FAFCF5","#244A3D"],"number":8},{"file":"09-charcoal-reader.png","name":"Полночь","desc":"Тёплый угольный фон, мягкое золото и контрастный светлый текст.","type":"Гротеск + моноширинные метаданные","shape":"2–4 px","layout":"Оглавление справа · заметки снизу","palette":["#1C1E1B","#E8E6DC","#C2AC77"],"number":9},{"file":"10-stone-reader.png","name":"Камень и бронза","desc":"Тёплые каменные оттенки, графит, бронза и асимметричная компоновка основного чтения.","type":"Геометрический гротеск","shape":"16 px и кнопки-капсулы","layout":"Заметки слева · оглавление снизу · инструменты справа","palette":["#E7E3DA","#393A35","#B49A62"],"number":10}];
for (const slot of ['A','B']) {
 const select=document.getElementById('select-'+slot);
 select.addEventListener('change',()=>{
  const variant=variants[Number(select.value)]; if(!variant)return;
  const img=document.getElementById('image-'+slot);img.src=variant.file;img.alt=variant.name+': '+variant.desc;
  document.getElementById('link-'+slot).href=variant.file;document.getElementById('full-'+slot).href=variant.file;
  document.getElementById('meta-'+slot).textContent=[variant.type,variant.shape].filter(Boolean).join(' · ');
  document.getElementById('layout-'+slot).textContent=variant.layout;
  const swatches=document.getElementById('swatches-'+slot);swatches.replaceChildren(...variant.palette.map(color=>{const item=document.createElement('i');item.style.background=color;item.title=color;return item;}));
 });
}

})();
